# Generated by Django 4.2.2 on 2023-06-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_assignee_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignee',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task'),
        ),
    ]
