# Generated by Django 4.2.2 on 2023-06-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tag_task_created_at_task_updated_at_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
